
# enable stemming of words in the content
enable_stemming: true

# filtering the feature vectors

# keep/drop numbers from the contents
filter_numbers: true

# filtering feature vector of each doc
# a value of <=1 will include all words
filter_words_less_than: 4

# just retain top-k words in feature vector 
# based on tf-idf ranking
# any value less than 0 will retain all words
retain_top_k_words: 10


# if save_output is enabled output_file should 
# be specified
save_output: false
output_file: "./output.txt"
# if false it will not store the tf-idf scores for each words
# but the words will be sorted based on tf-idf scores
persist_tf_idf_score: false
