
# enable stemming of words in the content
enable_stemming: true

# filtering the feature vectors

# keep/drop numbers from the contents
filter_numbers: true

# filtering feature vector of each doc
# a value of <=1 will include all words
filter_words_less_than: 4

# just retain top-k words in feature vector 
# based on tf-idf ranking
# any value less than 0 will retain all words
retain_top_k_words: 512

# if enabled output files are stored in CSV format
# 1) Transaction data format is stored as output-tdf.csv
# 2) Data matrix format is stored as output-dmf.csv
# NOTE: If the file already exists, it will be overwritten
save_output: true