
# enable stemming of words in the content
enable_stemming: true

# filtering the feature vectors

# keep/drop numbers from the contents
filter_numbers: true

# filtering feature vector of each doc
# a value of <=1 will include all words
filter_words_less_than: 4

# just retain top-k words in feature vector 
# based on tf-idf ranking
# any value less than 0 will retain all words
# NOTE: In transaction data format top k words of
# each document will be retained. In data matrix format
# top k words of the corpus will be retained.
retain_top_k_words: 512

# all output files/folders will be written to this location
output_dir: "./output"